export const CHANGE_DEGREES_TO_CELSIUS = 'CHANGE_DEGREES_TO_CELSIUS'
export const CHANGE_DEGREES_TO_FAHRENHEIT = 'CHANGE_DEGREES_TO_FAHRENHEIT'

export const CHANGE_THEME_TO_LIGHT = 'CHANGE_THEME_TO_LIGHT'
export const CHANGE_THEME_TO_DARK = 'CHANGE_THEME_TO_DARK'